import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // supabase/functions is Deno, not browser: npm: specifiers and the Deno
  // global don't parse under this browser/Node-oriented config.
  { ignores: ["dist", "supabase/functions"] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  {
    // shadcn primitives are generated by the CLI and re-generated on upgrade -
    // the empty wrapper interfaces are that generator's house style, and
    // hand-editing them here would just be undone next time.
    files: ["src/components/ui/**/*.{ts,tsx}"],
    rules: { "@typescript-eslint/no-empty-object-type": "off" },
  },
  {
    // Known debt, deliberately scoped: the hand-rolled RFC5545/RRULE parser
    // and the calendar page it feeds pass untyped ICS records around. Kept as
    // warnings so the build stays green while remaining visible, instead of
    // being switched off project-wide - `any` is still an error everywhere
    // else, so new code can't quietly add more.
    files: ["src/integrations/calendar/sync.ts", "src/pages/CalendarPage.tsx"],
    rules: { "@typescript-eslint/no-explicit-any": "warn" },
  },
);
